@base = http://localhost:8090

#### Basic Metadata
GET {{base}}

#### Create a Device
POST {{base}}/api/devices
Content-Type: application/json

{
  "activeFlag": 0,
  "apiFlag": 8,
  "code": "string",
  "deviceIMEICode": "streefgging",
  "gsmCode": "string",
  "id": 0,
  "name": "string",
  "remarks": "string",
  "updatedAt": "2020-03-20T15:38:56.072Z",
  "updatedBy": 0,
  "sensor": "jkd"
}