@base = http://localhost:8080/api

#### Login
POST {{base}}/auth/login
Content-Type: application/json

{
    "userName":"user",
    "password":"password"
}

#### Login
GET {{base}}/auth/me
Authorization: Bearer dXNlcjpwYXNzd29yZA==
Content-Type: application/json

#### Login
POST {{base}}/auth/logout
Authorization: Bearer dXNlcjpwYXNzd29yZA==
Content-Type: application/json
