version: '3.1'

services:
  mysql:
    image: tobi312/rpi-mariadb
    container_name: "mysql"
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MULTIPLE_DATABASES: comment_db,tracker_db
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      
  postgres:
    image: "postgres:11"
    container_name: "my_postgres"
    environment:
      POSTGRES_DB: keyclock_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password   
    ports:
      - "54320:5432"
