version: "3.3"

services:
  gurukulam-postgres:
    image: postgres:11
    container_name: gurukulam_postgres
    environment:
      POSTGRES_DB: practice_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
