version: "3.1"

services:
  postgres:
    image: "postgres:11"
    container_name: "my_postgres"
    environment:
      POSTGRES_DB: practice_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
  flowable:
    image: "flowable/all-in-one"
    container_name: "my_flowable"
    ports:
      - "8080:8080"
