@base = https://gurukulam.techatpark.com/api 
#### Login
# @name login 
POST {{base}}/auth/login
Content-Type: application/json

{
    "userName": "tom",
    "password": "password"
}

#### Create Practice
# @name practice
POST {{base}}/practices/java
Authorization: Bearer {{login.response.body.authToken}}
Content-Type: application/json

{
	"name":"practice1",
	"description":"exam1"
}


#### Create single line question
POST {{base}}/practices/java/{{practice.response.body.id}}/questions/SINGLE_LINE
Authorization: Bearer {{login.response.body.authToken}}
Content-Type: application/json

{
    
    "question": "string",
    "answer": "string"
}

#### Create new multi line question
POST {{base}}/practices/java/{{practice.response.body.id}}/questions/MULTI_LINE
Authorization: Bearer {{login.response.body.authToken}}
Content-Type: application/json

{
    "question": "string",
    "answer": "string"
}

#### Create new choose the best question
POST {{base}}/practices/java/{{practice.response.body.id}}/questions/CHOOSE_THE_BEST
Authorization: Bearer {{login.response.body.authToken}}
Content-Type: application/json

{
  "question": "string",
  "choices": [
    {
      "value": "string",
      "answer": true
    },
    {
      "value": "string",
      "answer": true
    }
  ]
}

#### Create new multi choice question
POST {{base}}/practices/java/{{practice.response.body.id}}/questions/MULTI_CHOICE
Authorization: Bearer {{login.response.body.authToken}}
Content-Type: application/json

{
  "question": "string",
  "answer": "string",
  "choices": [
    {
      "id": 0,
      "value": "string",
      "answer": true
    }
  ]
}

#### Logout current user
POST {{base}}/auth/logout
Authorization: Bearer {{login.response.body.authToken}}
Content-Type: application/json