@base = http://localhost:8080/api
#### Login
# @name login 
POST {{base}}/auth/login
Content-Type: application/json

{
    "userName":"user",
    "password":"password"
}

#### Create Exam
POST {{base}}/exams/sql
Authorization: Bearer {{login.response.body.authToken}}
Content-Type: application/json

{
    "name": "HR DB",
    "database": "h2",
    "script": "SELECT 1s"
}

#### List Exams
GET {{base}}/exams/sql
Authorization: Bearer {{login.response.body.authToken}}
Content-Type: application/json

#### Logout
POST {{base}}/auth/logout
Authorization: Bearer {{login.response.body.authToken}}
Content-Type: application/json