@base = http://localhost:8080/api

#### Create Exam
POST {{base}}/exams/sql
Content-Type: multipart/form-data; 

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="exam"

{"name":"HR DB","database":"postgres"}
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="scripts"; filename="1.sql"
Content-Type: application/text
< ./src/test/resources/postgres/scripts/1.sql
< ./src/test/resources/postgres/scripts/2.sql
------WebKitFormBoundary7MA4YWxkTrZu0gW--

#### List Exams
GET {{base}}/exams/sql