spring:
  profiles:
    active: @spring.profiles.active@
  application:
    name: Gurukulam API
    version: 2.0
  ## Database
  datasource:
    jdbcUrl: jdbc:h2:mem:practice_db;INIT=create schema if not exists practice_db\;
    username: sa
    password: password
    postgresql:
      jdbcUrl: jdbc:postgresql://localhost:5432/practice_db
      username: user
      password: password
  ## Security
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${GOOGLE_CLIENT_ID}
            clientSecret: ${GOOGLE_SECRET}
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
  jackson:
    default-property-inclusion: non_null
## Open API
springdoc:
  packagesToScan: com.gurukulams,com.gurukulams.starter.security.controller
  swagger-ui:
    operationsSorter: method
    tagsSorter: alpha
app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751926D96C90030DD58429D2751AC1BDBBC926D96C90030DD58429D2751AC1BDBBC926D96C90030DD58429D2751AC1BDBBC926D96C90030DD58429D2751AC1BDBBC926D96C90030DD58429D2751AC1BDBBC926D96C90030DD58429D2751AC1BDBBC926D96C90030DD58429D2751AC1BDBBCAC1BDBBC
    tokenExpirationMsec: 864000000
  seed:
    folder: ./gurukulams-core/src/main/resources/data
  oauth2:
    # After successfully authenticating with the OAuth2 Provider,
    # we'll be generating an auth token for the user and sending the token to the
    # redirectUri mentioned by the client in the /oauth2/authorize request.
    # We're not using cookies because they won't work well in mobile clients.
    authorizedRedirectUris:
      - http://localhost/oauth2/redirect
      - myandroidapp://oauth2/redirect
      - myiosapp://oauth2/redirect

admins:
  12-biology: jerry
  12-physics: jerry

logging:
  level:
    root: DEBUG
  pattern:
    console: '%black(%d{ISO8601}) %highlight(%-5level) [%blue(%t)] %yellow(%C{1.}): %msg%n%throwable'
    file: '%d %p %C{1.} [%t] %m%n'
  logback:
    rollingpolicy:
      file-name-pattern: ./logs/archived/api-logger-%d{yyyy-MM-dd}.%i.log
      max-file-size: 10MB
  file:
    name: ./logs/api-logger.log