spring:
  ## Database
  datasource:
    url: jdbc:postgresql://localhost:5432/practice_db
    username: user
    password: password

## Open API
springdoc:
  packagesToScan: com.techatpark.gurukulam

