spring:
  application:
    name: Gurukulam
  ## Database
  datasource:
    jdbcUrl: jdbc:h2:mem:practice_db
    username: sa
    password: password
    postgresql:
      jdbcUrl: jdbc:postgresql://localhost:5432/practice_db
      username: user
      password: password

## Open API
springdoc:
  packagesToScan: com.techatpark.gurukulam
