spring:
  application:
    name: Gurukulam API
  ## Database
  datasource:
    jdbcUrl: jdbc:h2:mem:practice_db
    username: sa
    password: password
    postgresql:
      jdbcUrl: jdbc:postgresql://localhost:5432/practice_db
      username: user
      password: password
security:
  require-ssl: true
http:
  port: 8080
server:
  port: 8443
  http2:
    enabled: true
  ssl:
    key-store-type: PKCS12
    key-store: "classpath:localhost.p12"
    key-store-password: javatoday
    key-alias: localhost
## Open API
springdoc:
  packagesToScan: com.techatpark.gurukulam
